// Autogenerated from Pigeon (v1.0.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class Profile;
@class BootConfig;

@interface Profile : NSObject
@property(nonatomic, copy, nullable) NSString * name;
@property(nonatomic, copy, nullable) NSString * avatarUrl;
@property(nonatomic, copy, nullable) NSString * email;
@property(nonatomic, copy, nullable) NSString * mobileNumber;
@end

@interface BootConfig : NSObject
@property(nonatomic, copy, nullable) NSString * pluginKey;
@property(nonatomic, copy, nullable) NSString * memberId;
@property(nonatomic, copy, nullable) NSString * memberHash;
@property(nonatomic, strong, nullable) Profile * profile;
@property(nonatomic, copy, nullable) NSString * unsubscribed;
@property(nonatomic, copy, nullable) NSString * trackDefaultEvent;
@property(nonatomic, copy, nullable) NSString * hidePopup;
@end

/// The codec used by ChannelIOApi.
NSObject<FlutterMessageCodec> *ChannelIOApiGetCodec(void);

@protocol ChannelIOApi
- (nullable NSString *)bootConfig:(BootConfig *)config error:(FlutterError *_Nullable *_Nonnull)error;
- (nullable NSString *)testWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void ChannelIOApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<ChannelIOApi> *_Nullable api);

NS_ASSUME_NONNULL_END
